// Manisha/handson_08/src/components/Header.vue
<template>
  <header class="header">
    <RouterLink to="/" class="site-name">Student Portal</RouterLink>
    <nav>
      <ul class="nav-list">
        <li><RouterLink to="/" class="nav-link">Home</RouterLink></li>
        <li><RouterLink to="/courses" class="nav-link">Courses</RouterLink></li>
        <li><RouterLink to="/profile" class="nav-link">Profile</RouterLink></li>
        <li class="badge">Enrolled: {{ store.enrolledCourses.length }}</li>
      </ul>
    </nav>
  </header>
</template>

<script setup>
import { useEnrollmentStore } from '../stores/enrollment'
const store = useEnrollmentStore()
</script>

<style scoped>
.header {
  background-color: #1a73e8;
  color: white;
  padding: 16px 32px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.site-name {
  font-size: 1.5rem;
  font-weight: bold;
  color: white;
  text-decoration: none;
}
.nav-list {
  list-style: none;
  display: flex;
  gap: 24px;
  align-items: center;
}
.nav-link {
  color: white;
  text-decoration: none;
  font-size: 1rem;
}
.badge {
  background-color: white;
  color: #1a73e8;
  padding: 4px 12px;
  border-radius: 20px;
  font-weight: bold;
  font-size: 0.9rem;
}
</style>

// Manisha/handson_05/src/components/Header.jsx
function Header({ siteName, enrolledCount }) {
  return (
    <header style={styles.header}>
      <span style={styles.siteName}>{siteName}</span>
      <nav>
        <ul style={styles.navList}>
          <li><a href="#" style={styles.navLink}>Home</a></li>
          <li><a href="#" style={styles.navLink}>Courses</a></li>
          <li><a href="#" style={styles.navLink}>Profile</a></li>
          <li style={styles.enrolledBadge}>Enrolled: {enrolledCount}</li>
        </ul>
      </nav>
    </header>
  );
}

const styles = {
  header: {
    backgroundColor: '#1a73e8',
    color: 'white',
    padding: '16px 32px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  siteName: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
  navList: {
    listStyle: 'none',
    display: 'flex',
    gap: '24px',
    alignItems: 'center',
  },
  navLink: {
    color: 'white',
    textDecoration: 'none',
    fontSize: '1rem',
  },
  enrolledBadge: {
    backgroundColor: 'white',
    color: '#1a73e8',
    padding: '4px 12px',
    borderRadius: '20px',
    fontWeight: 'bold',
    fontSize: '0.9rem',
  }
};

export default Header;
